### ISSUE TITLE
Problems to get it running

### ISSUE THREAD

**Issue by mspreitz** [JesusMcCloud/magnumpi#5]
I tried to use the magnumpi today, but I didn't get it working.

After connecting the device I can choose the app that I'd like to analyze. Afterwards nothing happens. All windows keep being empty, even the log window.

The device is rooted (Android 4.4.4), xposed as well as magnumpi are running and no error message is displayed.

Do you have any idea how to fix this?

**Comment by JesusMcCloud** [comment]
Did you make sure that the app you are trying to analyse was not running when you started the analysis session? Probably the best way to make sure that the app is not running is to force-stop it from the application's app info screen.

The Magnum PI service needs to be running before the app to be analysed is started, because what actually happens when an app is started and the Magnum PI Xposed module is active is that every app tries to connect to the socket of the Magnum PI service. This is done *only* immediately after starting an app to check if Hooks are enabled for this app.
There might also be an issue (depending on your Android rom) if you are trying to use adb and USB networking simultaneously, so it could be possible that you won't see any logcat output, but apart from that, Magnum PI should still work.

Btw: Did you build MagnumPI yourself or fetch the prebuilt version from http://magnumpi.org?

**Comment by mspreitz** [comment]
thanks a lot, I'm not sure why it is now running, but after a reboot of all systems and a restart of Magnum Pi it is now working!

Nice Tool!
